Sohbet/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Models;
using BLL;
using DAL;
namespace Sohbet.Controllers
{
    public class MessageController : Controller
    {
        BLLMessages<Message> bLLMessages = new BLLMessages<Message>();
       BLLUser<User> bLLUser = new BLLUser<User>();
        MessageSettings<Message> Messages = new MessageSettings<Message>();
        Context context = new Context();
        // GET: Message
        public ActionResult Index()
        {
            int id = Convert.ToInt32(Session["ID"]);
            TempData["Users"] = bLLUser.List().Where(u=>u.UserID!=id).ToList();
            return View();
        }
        //AJAX
        public JsonResult MessagesPerson(int? id)
        {
            int userID = Convert.ToInt32(Session["UserID"]);
            var messages = bLLMessages.List();
            return Json(messages.OrderByDescending(m => m.MessageID), JsonRequestBehavior.AllowGet);
        }
        public ActionResult SendMessage(Message message)
        {
            int id = Convert.ToInt32(Session["ID"]);
            message.SenderID = id;
            message.Seen = false;
            message.Date = DateTime.Now;
            bLLMessages.Add(message);
            return RedirectToAction("../Page/Home");
        }
        public ActionResult Clear(int id)
        {
            int userID = Convert.ToInt32(Session["ID"]);
            var list = context.Messages.Where(m => m.SenderID == id && m.RecipientID == userID || m.SenderID == userID && m.RecipientID == id).ToList();
            foreach (var item in list)
            context.Messages.Remove(item);
            context.SaveChanges();
            return RedirectToAction("../Page/Home");
        }
        [HttpPost]
        public ActionResult DeleteMessage()
        {
            return View();
        }

    }
}

Sohbet/Controllers/PageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sohbet.VMmodels;
using BLL;
using Models;
using ModelsView;
using DAL;
namespace Sohbet.Controllers
{
    public class PageController : Controller
    {

        BLLUser<User> setting = new BLLUser<User>();
        BLLMessages<Message> messages = new BLLMessages<Message>();
        // GET: Page
        public ActionResult Home()
        {
            Users();
            return View();
        }
        public void Users()
        {
            int id = Convert.ToInt32(Session["ID"]);
            TempData["Users"] = setting.List().Where(u => u.UserID != id).ToList();
        }
        public ActionResult SignUpPage()
        {
            return PartialView();
        }
        public ActionResult About()
        {
            Users();
            return View();
        }
        public ActionResult Contact()
        {
            Users();
            return View();
        }
        public ActionResult Login()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult Login(VMLogin login)
        {
            var user = setting.List().Where(u => u.UserName == login.UserName && u.Password == login.Password).SingleOrDefault();
            if (user != null)
            {
                Session["ID"] = user.UserID;
                Session["Status"] = user.status;
                Session.Timeout=2;
            }
            else
            {
                ViewBag.Hata = "Hatalı bilgi girişi. Tekrar Dene.";
            }
            return RedirectToAction("Home");
        }
        public ActionResult LoginOK()
        {
            Context context = new Context();
            VMLoginOK oK = new VMLoginOK();
            int id=Convert.ToInt32(Session["ID"]);
            oK.user = setting.List().Where(u => u.UserID == id).SingleOrDefault();
            oK.Messages = context.Messages.Where(m=>m.RecipientID==id && m.Seen==false).ToList();
            return PartialView(oK);
        }
      
        public ActionResult Out()
        {
            Session.Abandon();
            return RedirectToAction("Home");
        }
        public ActionResult PageSendMessage()
        {
            return PartialView();
        }
    }
}

Sohbet/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sohbet.VMmodels;
using BLL;
using Models;
using DAL;
namespace Sohbet.Controllers
{
    public class UserController : Controller
    {
        BLLUser<User> Datas = new BLLUser<User>();
        // GET: User
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SingUp(User user)
        {
            Datas.Add(user);
            return RedirectToAction("/Page/Home");
        }
        public ActionResult Forgot()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Forgot(string eposta)
        {
            return View();
        }
        public ActionResult MyProfile()
        {
            int id = Convert.ToInt32(Session["ID"]);
            return View(Datas.Find(id));
        }
        public ActionResult Settings()
        {
            int id = Convert.ToInt32(Session["ID"]);
            return View(Datas.Find(id));
        }
        [HttpPost]
        public ActionResult Settings(User user)
        {
            Datas.Update(user);
            Session.Abandon();
            return View();
        }
    }
}

Sohbet/Views/Message/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
<div class="container-md">
  <div style="width:100%;height:800px;background-color:floralwhite; opacity:0.5;">

  </div>
</div>

Sohbet/Views/Page/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>About</h2>

<div class="container">
    <h1> VİZYON</h1>
    <p>
        Sanal platformda kullanıcılarına çağın gerektirdiği alt yapıyı hazırlayarak kaliteli bir sohbet ortamını yaratmak. Bu altyapı ile alanında kendini Türkiye’ de 1. Sıralara taşıyarak chat ve sohbet ortamında kendini ispatlamış bir kurum olmaktır.
    </p>
    <h1>MİSYON</h1> 
    <p>
        Platformumuza giren her üyemizin aktif katılımını sağlayarak eşsiz ve eğlenceli bir sohbet ortamına dahil etmek. Üyelerimizin keyifli bir sohbet içinde hem oyun kanallarımızla yarışmalarla hem de sohbet kanallarımızda arkadaşlık ve dostluklarla pekiştirilmiş güvenli bir sohbet ortamını yaratarak alanında tek tercih edilen sohbet platformu olmaktır.
    </p></div>

Sohbet/Views/Page/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Contact</h2>
<div class="container">
    <p>
        E-Posta:
        HuseyinToprak96@outlook.com
    </p>
    <p>
        Telefon: 0555 003 9619
    </p>
    <p>
        Sitede anlık olarak bulunan tüm adminlere ulaşım sağlamak isterseniz lütfen #OperHelp odasına giriş yaparak irtibat kurunuz.
    </p></div>

Sohbet/Views/Page/Home.cshtml
@model Models.User
@using Models
@{ ViewBag.Title = "Home";
                Layout = "~/Views/Shared/_Layout.cshtml"; }

<div class="photos">
    <marpuee behavior="scroll" direction="left">
        @foreach (User user in ((List<User>)TempData["Users"]))
        {
<a href="/User/Face/id=@user.UserID"> <img src="@user.Photo" height="80" width="80" /></a>}
    </marpuee>
</div>

<hr />

<section>
    <aside>
        @if (Session["ID"] != null)
        {
<div class="userList">
    <ul>
        @foreach (User user in ((List<User>)TempData["Users"]))
        {
<li>  <button class="btn-primary" value="@user.UserID">@user.UserName</button></li>}
    </ul> <br />
</div>            }
    </aside>
    <article>
        @if (Session["ID"] == null)
        {
            using (Html.BeginForm("SignUp", "User", FormMethod.Get))
            {
<div class="form form-select-sm">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })
            <input type="file" />
            @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Retry Password", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Mail, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Mail, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Mail, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn accordion-flush" />
        </div>
    </div>
</div> }
            }
            else
            {

<nav id="navbar-example2" class="navbar navbar-light bg-light px-3">
    <a class="navbar-brand" id="clickUser" href="#">Messages</a>
    <div id="allClear"></div>
    <ul class="nav nav-pills">
        <li class="nav-item">
            <a class="nav-link" href="#scrollspyHeading1">Inbox</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#scrollspyHeading2">Outbox</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Dropdown</a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#scrollspyHeading3">Third</a></li>
                <li><a class="dropdown-item" href="#scrollspyHeading4">Fourth</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#scrollspyHeading5">Fifth</a></li>
            </ul>
        </li>
    </ul>
</nav>
                <div data-bs-spy="scroll" data-bs-target="#navbar-example2" data-bs-offset="0" class="scrollspy-example" tabindex="0">

                    <div id="messages">
                    </div>
                    @Html.Action("PageSendMessage")
                </div>            }
    </article>
</section>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<style>
    #messages {
        height: 300px;
        width: 600px;
        overflow-y: scroll;
        scroll-padding-top: 100%;
        scroll-snap-stop: always;
    }

    section {
        display: grid;
        grid-template-columns: 20% 80%;
        grid-template: subgrid;
    }

    .photos {
        margin-left: 50px;
    }

        .photos img {
            opacity: 0.2;
            transition: all 0.2s 0.2s ease-in-out;
        }

            .photos img:hover {
                opacity: 1;
                transform: scale(1.2)
            }
</style>

Sohbet/Views/Page/Login.cshtml
@model Sohbet.VMmodels.VMLogin
@using (Html.BeginForm("Login", "Page", FormMethod.Post))
{
    <div class=" align-content-sm-start">
        <table>
            <tr>
                <td>
                    Username
                </td>
                <td>
                    @Html.TextBoxFor(m => m.UserName)
                </td>
            </tr>
            <tr>
                <td>
                    Password:
                </td>
                <td>
                    @Html.TextBoxFor(m => m.Password)
                </td>
            </tr>
            <tr>
                <td colspan="2"><input type="submit" value="Login" /></td>
            </tr>
            <tr>
                <td>
                    @Html.ActionLink("Şifremi Unuttum","Forgot","Page")
                </td>
                <td>

                </td>
            </tr>
        </table>
    </div>      }

Sohbet/Views/Page/LoginOK.cshtml
@model ModelsView.VMLoginOK
<div class=" align-content-sm-start">
    <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
        <button type="button" class="btn btn-danger">My Profile</button>
        <button type="button" class="btn btn-danger">Settings</button>
        <button type="button" class="btn btn-danger">
            @Html.ActionLink("LogOut", "Out", new { @class = "btn btn-danger" })
        </button>
    </div>
</div>
<style>
    a {
        color: white;
    }

        a:hover {
            color: white;
        }
</style>

Sohbet/Views/Page/PageSendMessage.cshtml
@model Models.Message
<div id="sendComp">
    @using (Html.BeginForm("SendMessage", "Message", FormMethod.Get)) {
    <div class="mb-3" id="noSeen">
        @Html.TextBoxFor(m=>m.RecipientID, new { @id = "id1" })
    </div>  
<div class="mb-3">
    @Html.TextBoxFor(m=>m.MessageContent)
</div>
<div><input type="submit" class="buton btn-info" onclick="sendMessage()" id="send"/></div>
    } </div> 
<script>
    function sendMessage() {
        var btn = document.getElementById("send");
        var txt = document.getElementById("e");
        var div = document.getElementById("messages");
        var id1 = document.getElementById("id");
        var id2 = document.getElementById("id1");
        var message = document.createElement("div");
        if (txt.value != "") {
            message.innerText = txt.value;
        message.className = "rightSender";
        txt.value = "";
            div.appendChild(message);
        }
    }
</script>

Sohbet/Views/Page/SignUpPage.cshtml
@using (Html.BeginForm("SingUp", "User", FormMethod.Post))
{
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })
                <input type="file" />
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Retry Password", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mail, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn accordion-flush" />
            </div>
        </div>
    </div>
}

Sohbet/Views/Shared/_Layout.cshtml
@using Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Online Chat</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body onload="Show();">
    <ul class="nav justify-content-end">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/Page/Home">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Page/About">About</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Page/Contact">Contact</a>
        </li>
    </ul>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("İs Div a Chene The lip am", "Index", "Home", new { area = "" }, new { @class = "title" })
                @if (Session["ID"] == null)
                {
                    @Html.Action("Login")
                }
            else
            {
               @Html.Action("LoginOK")
            }

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>
    <div class="containerRender">
 <div>
     @RenderBody()
 </div>
        <footer>
            <button type="button" class="btn btn-dark" id="liveToastBtn">Show live toast</button>

            <div class="position-fixed bottom-0 end-0 p-3" style="z-index: 11">
                <div id="liveToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
                    <div class="toast-header">
                        <img src="..." class="rounded me-2" alt="...">
                        <strong class="me-auto">Bootstrap</strong>
                        <small>11 mins ago</small>
                        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                    </div>
                    <div class="toast-body">
                        Hello, world! This is a toast message.
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>
<style>
    #linkClear{
        color:black;
    }
    body {
        background: url('../../image/banner.jpg');
    }
   
    .title{
       font-size:30px;
       color:black;
       font-weight:bold;
       text-decoration:none;
    }
    #id, #id1{
        display:none;
    }
</style>
<script>
    function Show() {
        personMessage();
    }
    function personMessage() {
        var btnUser = document.getElementsByClassName("btn-primary");
        var div = document.getElementById("messages");
        var u = document.getElementById("clickUser");
        var send = document.getElementById("sendComp");
        var id1 = document.getElementById("id1");
        var allClear = document.getElementById("allClear");
        var link = document.createElement("a");
        link.id = "linkClear";
        for (var i = 0; i < btnUser.length; i++) {
            btnUser[i].addEventListener("click", function () {
                link.innerText = "All Clear";
                link.href = "/Message/Clear/" + this.value;
                allClear.appendChild(link);
                factorySettings();
                send.style.display = "block";
                this.style.backgroundColor = "Red";
                u.innerText = this.innerText;
                var id = this.value;
                id1.value = "";
                id1.value = id;
                div.innerHTML = "";
                var xhr = new XMLHttpRequest();
                xhr.onreadystatechange = function () {
                    if (xhr.readyState == 4 && xhr.status == 200) {
                        var myDatas = JSON.parse(xhr.responseText);
                        let datas = Array.from(myDatas)
                        for (var j = 0; j < datas.length; j++) {
                            var mC = document.createElement("div");
                            var x = document.getElementById("id");
                            if (datas[j].SenderID == id && datas[j].RecipientID == x.innerText) {
                                mC.className = "leftSender";
                                mC.innerText = datas[j].MessageContent;
                                div.appendChild(mC);
                            }
                            else if (datas[j].RecipientID == id || datas[j].SenderID == x.innerText) {
                                mC.className = "rightSender";
                                mC.innerText = datas[j].MessageContent;
                                div.appendChild(mC);
                            }

                        }
                    }
                };
                xhr.open("GET", "/Message/MessagesPerson", true);
                xhr.send();

            });
        }
    }
    function factorySettings() {
        var btnUser = document.getElementsByClassName("btn-primary");
        for (var i = 0; i < btnUser.length; i++) {
            btnUser[i].style.backgroundColor = "blue";
        }
    }

</script>
<style>
    .leftSender {
        margin-left: 50px;
        border-radius: 15px;
        border: 1px solid;
        background-color: gold;
        width: 250px;
        height: 60px;
        font-size: 20px;
        padding-left: 30px;
        padding-top: 10px;
        color: darkblue;
    }
    .rightSender {
        margin-left: 300px;
        border-radius: 15px;
        border: 1px solid;
        background-color: blueviolet;
        width: 250px;
        height: 60px;
        font-size: 20px;
        padding-left:30px;
        padding-top: 10px;
        color: floralwhite;
    }
    .userList{
        position:relative;
        height:max-content;
        width:max-content;
        margin-top:70px;
    }
    .containerRender{
        background-color:antiquewhite;
    }
    li{
        list-style-type:none;
    }
    a{
        text-decoration:none;
    }
    #sendComp{
        display:none;
    }
</style>

Sohbet/Views/User/Index.cshtml
@model Models.User

@{
    ViewBag.Title = "Index";
}

<h2>Sign Up</h2>


@using (Html.BeginForm("Index","User",FormMethod.Post)) 
{
<div class="form-horizontal">

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Photo, new { htmlAttributes = new { @class = "form-control" } })
            <input type="file" />
            @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Retry Password", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Mail, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Mail, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Mail, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn accordion-flush" />
        </div>
    </div>
</div>
}
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>